name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main
  pull_request:

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - run: sudo apt install --yes graphviz graphviz-dev
    - name: Install pip dependencies
      run: |
        pip install -r requirements.txt

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .

    # Make artifact visible in github actions
    - uses: actions/upload-artifact@v3
      with:
        name: dmsc-school-book
        path: ./_build/html

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
      if: github.ref_name == 'main'
