name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main
  pull_request:

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
    - uses: actions/checkout@v3
        
    # Set up Miniconda
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.10'
        activate-environment: myenv

    # Create the Conda environment and install dependencies
    - name: Create Conda environment
      run: |
        conda init bash
        source ~/.bashrc
        conda create -n myenv python=3.10 -y
        source activate myenv
        conda install -c conda-forge mcstas graphviz -y

    - name: Install pip dependencies
      run: |
        conda activate myenv
        pip install -r requirements.txt

    # Build the book
    - name: Build the book
      run: |
        conda activate myenv
        jupyter-book build .

    # Make artifact visible in github actions
    - uses: actions/upload-artifact@v3
      with:
        name: dmsc-school-book
        path: ./_build/html

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
        force_orphan: true
      if: github.ref_name == 'main'
